Still working on Diagnostics
Contexts have been moved to their own source/header files.

Added SelectorContext which is a single context on its own, or used
within a HighlightContext. It looks like this:

In Assembler.cpp:44:60: Error: Invalid punctuation
In Assembler.cpp:44:64: Note: Missing punctuation at end of sentence
	Some rather long line that contains an invalid word called seet
	                                                               ^
	                                                               (.!?)